SOURCE_DIR  := src
OUTPUT_DIR  := classes

JFLAGS = -g
JC = javac
JAVA = java



default: all


all:
	$(JC) $(JFLAGS) src/Node.java src/FibonacciHeap.java src/keywordcounter.java
		

clean:
		$(RM) *.class
		